---
- name: Create job template for create-incident
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx

  tasks:
    - name: Post create-incident job template
      role:
        user: student
        role: execute
        job_templates:
          - "Create incident (incident-create.yml)"
        controller_username: admin
        controller_password: ashutosh
        validate_certs: false