---
- name: Create job template for create-incident
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  tasks:
    - name: Post create-incident job template
      job_template:
        name: "Create incident (incident-create.yml)"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "ServiceNow"
        playbook: "incident-create.yml"
        execution_environment: "ServiceNow EE"
        use_fact_cache: false
        credentials:
          - "servicenow credential"
        state: "present"
        controller_host: "https://localhost"
        controller_username: admin
        controller_password: ashutosh
        validate_certs: false